application: ajaxadd
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /crongc
  script: cron.py

- url: /favicon.ico
  static_files: icon.png
  upload: icon.png

- url: /.*
  script: main.py
